name: ci
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "main"
    tags:
      - "*"

env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  check-cache:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: glehmann/actions-setup@fix-use-cache
      with:
        version: 0.7.15
        # use-cache: "false"
